"use client";
import {useMemo,useRef,useState} from "react";
import {useMutation} from "convex/react";
import {api} from "../convex/_generated/api";

const templates=[["breaking","Breaking News"],["report","News Report"],["documentary","Documentary"]];
export default function Editor(){
 const videoRef=useRef<HTMLVideoElement>(null);
 const createProject=useMutation(api.projects.create);
 const uploadUrl=useMutation(api.files.generateUploadUrl);
 const attach=useMutation(api.files.attachToProject);
 const [projectId,setProjectId]=useState<string|null>(null),[videoUrl,setVideoUrl]=useState<string|null>(null);
 const [headline,setHeadline]=useState("Major Development Reported"),[template,setTemplate]=useState("breaking");
 const [duration,setDuration]=useState(45),[time,setTime]=useState(0),[busy,setBusy]=useState(false);
 const spec=useMemo(()=>({format:"9:16",duration,headline,breaking:template==="breaking",sourceLabel:"Source: Add your source",clips:[{id:"main",start:0,end:duration}]}),[duration,headline,template]);
 async function upload(file:File){setBusy(true);try{const url=await uploadUrl();const r=await fetch(url,{method:"POST",headers:{"Content-Type":file.type},body:file});if(!r.ok)throw new Error("Upload failed");const data=await r.json();const id=projectId??await createProject({name:file.name.replace(/\.[^.]+$/,""),editSpec:JSON.stringify(spec)});setProjectId(id);const attached=await attach({projectId:id,storageId:data.storageId,filename:file.name,mimeType:file.type});setVideoUrl(attached.url);}finally{setBusy(false)}}
 function seek(v:number){setTime(v);if(videoRef.current)videoRef.current.currentTime=v}
 return <main className="min-h-screen bg-[var(--bg)]"><header className="sticky top-0 z-20 border-b border-[var(--line)] bg-[var(--bg)]/95 backdrop-blur"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-4"><div><div className="text-sm font-bold">NewsCut</div><div className="text-[11px] text-[var(--muted)]">Mobile news video editor</div></div><button onClick={()=>createProject({name:headline||"Untitled News Edit",editSpec:JSON.stringify(spec)}).then(setProjectId)} className="rounded-xl bg-white px-4 py-2 text-xs font-bold text-black">New project</button></div></header>
 <section className="mx-auto grid max-w-6xl gap-4 p-4 lg:grid-cols-[1fr_360px]"><div className="space-y-4"><div className="flex min-h-[520px] items-center justify-center rounded-3xl border border-[var(--line)] bg-black p-3"><div className="relative aspect-[9/16] w-full max-w-[330px] overflow-hidden rounded-2xl bg-[#15171b]">{videoUrl?<video ref={videoRef} src={videoUrl} controls playsInline onLoadedMetadata={e=>setDuration(Math.round(e.currentTarget.duration))} onTimeUpdate={e=>setTime(e.currentTarget.currentTime)} className="h-full w-full object-cover"/>:<label className="flex h-full cursor-pointer flex-col items-center justify-center gap-3 p-8 text-center"><span className="text-4xl">＋</span><span className="text-sm font-semibold">Add your news video</span><span className="text-xs text-[var(--muted)]">MP4, MOV or WebM</span><input className="hidden" type="file" accept="video/*" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/></label>}<div className="pointer-events-none absolute left-3 right-3 top-3"><div className="inline-flex rounded bg-[var(--accent)] px-2 py-1 text-[10px] font-black tracking-wider">{template==="breaking"?"BREAKING":"NEWS"}</div><div className="mt-2 max-w-[90%] text-lg font-black leading-tight drop-shadow-lg">{headline}</div></div><div className="pointer-events-none absolute bottom-3 left-3 right-3 rounded-lg bg-black/70 px-3 py-2 text-[9px]">Source: Add your source</div></div></div>
 <div className="rounded-2xl border border-[var(--line)] bg-[var(--panel)] p-4"><div className="mb-3 flex justify-between text-xs"><span className="font-bold uppercase tracking-wider text-[var(--muted)]">Timeline</span><span className="text-[var(--muted)]">{time.toFixed(1)}s / {duration}s</span></div><input className="w-full" type="range" min="0" max={Math.max(duration,1)} step=".1" value={Math.min(time,duration)} onChange={e=>seek(Number(e.target.value))}/><div className="mt-3 grid grid-cols-3 gap-2">{[30,45,60].map(s=><button key={s} onClick={()=>setDuration(s)} className={"rounded-lg border px-3 py-2 text-xs "+(duration===s?"border-white bg-white text-black":"border-[var(--line)] bg-[var(--panel2)]")}>{s}s</button>)}</div></div></div>
 <aside className="space-y-4"><div className="rounded-2xl border border-[var(--line)] bg-[var(--panel)] p-4"><div className="mb-3 text-sm font-bold">News template</div>{templates.map(([id,name])=><button key={id} onClick={()=>setTemplate(id)} className={"mb-2 w-full rounded-xl border p-3 text-left "+(template===id?"border-white bg-white text-black":"border-[var(--line)] bg-[var(--panel2)]")}><div className="text-sm font-bold">{name}</div><div className="mt-1 text-[11px] opacity-70">9:16 vertical • manual editing</div></button>)}</div>
 <div className="rounded-2xl border border-[var(--line)] bg-[var(--panel)] p-4"><div className="mb-3 text-sm font-bold">Headline</div><input value={headline} onChange={e=>setHeadline(e.target.value)} maxLength={90} className="w-full rounded-xl border border-[var(--line)] bg-[var(--panel2)] px-3 py-3 text-sm outline-none focus:border-white"/><div className="mt-2 text-[11px] text-[var(--muted)]">{headline.length}/90</div></div>
 <label className="flex cursor-pointer items-center justify-center rounded-2xl bg-white px-4 py-3 text-sm font-bold text-black">{busy?"Uploading…":"Replace / upload video"}<input className="hidden" type="file" accept="video/*" disabled={busy} onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/></label>
 <div className="rounded-2xl border border-[var(--line)] bg-[var(--panel)] p-4 text-xs leading-5 text-[var(--muted)]"><div className="mb-1 font-bold text-white">MVP status</div>9:16 preview, Convex storage, templates, headline overlays and timeline controls are active. Real trimming, captions, audio, lower-thirds and MP4 rendering come next.</div></aside></section></main>
}